---
- hosts: servers
  remote_user: super
  become: true
  roles:
    - role: install-packages
      packages: 
      - nmap
      - traceroute
      - vim
      - nano
      - htop
    - role: dns
      nameservers: ["1.1.1.1", "8.8.8.8"]
    - role: elk