---
- name: Install pip and docker service
  apt:
    name: ["python3-pip", "docker.io"]
    state: present

- name: Run and enable docker
  systemd_service:
    name: docker
    state: started
    enabled: true

- name: Install docker and docker-compose
  pip:
    executable: pip3
    name: 
    # версии по документации: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
      - docker>1.25
      - docker-compose>=1.7.0,<2.0.0

- name: Ensure /opt/elk/ exists
  file: 
    path: /opt/elk 
    state: directory
  
- name: Copy docker-compose file
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/elk/docker-compose.yml

- name: Build container
  community.docker.docker_compose:
    project_src: /opt/elk
    build: true

- name: Re-create a ELK container
  community.docker.docker_container:
    name: elk
    image: sebp/elk
    state: present
    recreate: true
    exposed_ports:
      - 9200
      - 5601
      - 5044
      