---
- name: Install pip
  apt:
    name: ["python3-pip"]
    state: present
    update_cache: false

- name: Install docker and docker-compose
  pip:
    executable: pip3
    name: 
    # версии по документации: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
      - docker>1.25
      - docker-compose>=1.7.0,<2.0.0

- name: Run and enable docker
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure /opt/elk/ exists
  file: 
    path: /opt/elk 
    state: directory
  
- name: Copy docker-compose file
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/elk/docker-compose.yml

- name: Start ELK stack
  docker_compose:
    project_src: /opt/elk
    state: present