apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- range .Values.ingress.rules }}
    - host: {{ .host }}
      http:
        paths:
        - backend:
            service:
              name: {{ $.Release.Name }}-web
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
  {{- end }}
